//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUETaller
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        [ScaffoldColumn(false)]
        public int idPelicula { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = " El nombre es requerido"), MaxLength(55)]
        [Display(Name = "Nombre de Pelicula")]
        public string nombre { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Lanzamiento")]
        public System.DateTime fecha_lanzamiento { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = " La categoría es requerida"), MaxLength(55)]
        [Display(Name = "Categoría")]
        public string categoria { get; set; }

        [DataType(DataType.Duration)]
        [Required(ErrorMessage = " Debe ser un numero"), MaxLength(55)]
        [Display(Name = "Duración (Minutos)")]
        public string duracion { get; set; }
    }
}
